config/routes.rb
  Rails.application.routes.draw do
    root to: 'pages#welcome'

    get   '/ingresar'  => 'sessions#new'
    post  '/ingresar'  => 'sessions#create'
    delete 'salir'    => 'sessions#destroy'
    get   'mails_user_groups' => 'member_groups#mails'

    get '/users/list' => 'users#list', as: :users_list
    get '/users/manifest' => 'users#manifest', as: :users_manifest

    get '/users/manifest_file' => 'users#manifest_file', as: :users_manifest_file
    post '/users/manifest_file' => 'users#manifest_file'

    get '/users/manifest_full_file' => 'users#manifest_full_file', as: :users_manifest_full_file

    get '/meetings/list' => 'meetings#list', as: :meetings_list

    resources :users, except: [:index]
    resources :groups do
      resources :meetings do
        collection do
          get 'list' => 'meetings#index_for_group'
        end
      end
    end
    resources :meetings do
      get :autocomplete_user_name, on: :collection
    end
    resources :user_meetings
    resources :meeting_groups
    resources :member_groups
    resources :admin_groups,       only: [:create, :destroy]
    resources :password_resets,    only: [:new, :create, :edit, :update]

    resources :payments
    resources :polls do
      resources :opinions
    end
    resources :opinions
  end

app/models/meeting.rb
# == Schema Information
#
# Table name: meetings
#
#  id         :integer          not null, primary key
#  date       :date
#  desc       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  state      :string(255)
#  minutes    :text
#  place      :string(255)
#  title      :string(255)
#  start      :datetime
#  finish     :datetime
#

class Meeting < ActiveRecord::Base

  MINUTES_MAX_LENGTH = 20000

  has_many :user_meetings, dependent: :destroy
  has_many :users, through: :user_meetings

  has_many :meeting_groups, dependent: :destroy
  has_many :groups, through: :meeting_groups

  validates :minutes,
    presence:   true,
    length:     { maximum: MINUTES_MAX_LENGTH }

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  authorize_resource

  def index
    @meetings = Meeting.all
  end

  def index_for_group
    @group = Group.find(params[:group_id])
    @meetings = @group.meetings.order(date: :desc)
  end

  def list
    @meetings = Meeting.includes(:user_meetings).order(date: :desc).limit(50)
  end

  def new
    @meeting = Meeting.new
    @users = User.select(:id, :email, :first_name, :last_name)
  end

  def create
    @meeting = Meeting.new(meeting_params)
    create_or_update
  end

  def show
  end

  def edit
    @users = User.select(:id, :email, :first_name, :last_name)
  end

  # PATCH/PUT /meetings/1
  def update
    @meeting.update(meeting_params)
    create_or_update
  end

  # DELETE /meetings/1
  def destroy
    @meeting.destroy
    flash[:success] = t(:meeting_destroyed_successfully)
    redirect_to meetings_url
  end

  private

    def create_or_update()

      if params["userMeeting"].nil?
        @meeting.errors.add(:asistente, " es necesario")
        render 'new'
      else
        if params["meetingGroup"].nil?
          @meeting.errors.add(:espacio, " es necesario")
          render 'new'
        else

          if @meeting.save
            UserMeeting.where(:meeting_id => @meeting.id).destroy_all
            params["userMeeting"]["users"].each do |user|
              admin_group = UserMeeting.new
              admin_group.user_id = user
              admin_group.meeting_id = @meeting.id
              admin_group.save
            end

            MeetingGroup.where(:meeting_id => @meeting.id).destroy_all
            params["meetingGroup"]["groups"].each do |group|
              member_group = MeetingGroup.new
              member_group.group_id = group
              member_group.meeting_id = @meeting.id
              member_group.save
            end

            flash[:success] = action_name == 'create' ? t(:meeting_created_successfully) : t(:meeting_updated_successfully)
            # redirect_to @group
            redirect_to @meeting
          else
            render 'new'
          end
        end
      end
    end

    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meeting_params
      params.require(:meeting).permit(:date, :desc, :start, :finish, :minutes)
    end

end

app/views/meetings/_attendant_li.html.erb
<li data-user-id="<%= user_meeting.user_id %>">
  <span class="attendant">
    <span class="glyphicon glyphicon-user"></span>
    <%= link_to user_meeting.user.full_name, user_meeting.user %>
  </span>
</li>

app/views/meetings/_form.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-offset-1 col-md-10">

      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <% if action_name == 'new' %>
            <h2 class="panel-title"><%= t(:add_meeting).humanize %></h2>
          <% else %>
            <h2 class="panel-title"><%= t(:edit_meeting).humanize %></h2>
          <% end %>
        </div>

        <div class="panel-body">
          <%= form_for @meeting, html: {class: "form-horizontal"} do |f| %>

            <% if @meeting.errors.any? %>
              <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
                <h2>
                  <%= pluralize(@meeting.errors.count, "error") %> impidieron que se grabara la reunión:
                </h2>
                <ul>
                  <% @meeting.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.label t(:date_lit).humanize, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= f.date_select :date, :order => [:year, :month, :day], class: "form-control" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label t(:description).humanize, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= f.text_area :desc, class: "form-control" %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-sm-2 control-label" for="group_type">Espacios</label>
              <div class="col-sm-10">

                <select multiple id="meetingGroup_groups" name="meetingGroup[groups][]" class="select2-container select2-container-multi form-control">
                  <% selected_groups = @meeting.meeting_groups.map(&:group_id) %>
                  <% (current_user.admin? ? Group.all : (current_user.agroups | @meeting.groups)).each do |group| %>
                    <option <%= group.id.in?( selected_groups) ? "selected='selected'" : ''%> <%= current_user.admin? || group.id.in?(current_user.agroups.map(&:id)) ? "" : "locked=locked"%> value="<%= group.id %>"><%= group.name %></option>
                  <% end %>
                </select>
              </div>
            </div>

            <div class="form-group">
              <label class="col-sm-2 control-label" for="group_type">Asistentes</label>
              <div class="col-sm-10">
                <%= collection_select(:userMeeting, :users, @users, :id, :full_name_with_email, {:selected => @meeting.user_meetings.map(&:user_id), include_hidden: false}, {multiple: "multiple",class: "select2-container select2-container-multi form-control ng-valid ng-dirty"}) %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <div class="alert alert-info">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar"><span aria-hidden="true">&times;</span></button>
                  Recuerda que aquí sólo puedes agregar usuarios que ya tienen cuenta en este sitio. Si quieres agregar a alguien que no tiene cuenta, primero <%= link_to 'crea un usuario', new_user_path %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <label class="col-sm-2 control-label" for="group_type"><%= t(:start_time).humanize %></label>
              <div class="col-sm-10">
                <%= f.time_field :start, class: "form-control meeting_time_field" %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-sm-2 control-label" for="group_type"><%= t(:finish_time).humanize %></label>
              <div class="col-sm-10">
                <%= f.time_field :finish, class: "form-control meeting_time_field" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label t(:minutes), class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= f.text_area :minutes, class: "form-control", oninput: "this.editor.update()", rows: "4" %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <div class="alert alert-info">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar"><span aria-hidden="true">&times;</span></button>
                  En el cuadro de arriba puedes escribir el Acta. A medida que escribas, abajo aparecerá una vista previa del Acta. En este cuadro puedes usar comandos básicos para formatear el texto. Por ejemplo, usa <code>#</code> para obtener texto más grande (intenta escribir <code># Título del Acta</code>). Para un listado de posibilidades, visita <%= link_to 'esta guía', 'https://es.wikipedia.org/wiki/Markdown' %>. Aquí te dejamos un ejemplo de un Acta.
                  <pre># Acta Primera Reunión de la Comisión Democracia Digital

**Tabla:** En esta reunión se tratarán los siguientes temas:

1. El primer tema
2. El segundo tema (expone Cármen)

**Se inicia la sesión a las 19:00**

## Tema 1

* Luis: Creo que hay que hacer algo urgente.
* Cármen: De acuerdo

## Tema 2

* Cármen expone.
* Todos aplauden.</pre>
                </div>
              </div>
            </div>







            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit t(:save).humanize, class: "btn btn-primary" %>
              </div>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Vista previa</h2>
        </div>
        <div class="panel-body">
          <div id="minutes_preview">
          </div>
        </div>
      </div>
    </div>
  </div>

</div>


<script>
  function Editor(input, preview) {
    this.update = function () {
      preview.innerHTML = markdown.toHTML(input.value);
    };
    input.editor = this;
    this.update();
  }
  new Editor(document.getElementById("meeting_minutes"), document.getElementById("minutes_preview"));

  var textArea = $('#meeting_minutes');
  var preview = $('#minutes_preview');

  textArea.on('change keyup paste', function() {
    $(this).css('height', max(preview.parent().height(), '400px'));
  }).trigger('change');
</script>


<script type="text/javascript">
  $(document).ready(function() {
    $('#userMeeting_users').select2({
      placeholder: "Selecciona Asistentes",
      allowClear: true
    });
    $('#meetingGroup_groups').select2({
      placeholder: "Selecciona Espacios",
      allowClear: true
    });

  });
</script>

app/views/meetings/_organizing_group_li.html.erb
<li data-group-id="<%= meeting_group.group_id %>">
  <span class="organizing_group">
    <%= link_to meeting_group.group.name, meeting_group.group %>
  </span>
</li>

app/views/meetings/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h2 class="panel-title"><%= t(:meetings).humanize %></h2>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <table id="datatable" class="table table-bordered responsive no-wrap">
              <thead>
                <tr>
                  <th><%= t(:title).humanize %></th>
                  <th><%= t(:groups).humanize %></th>
                  <th><%= t(:attendants).humanize %></th>
                  <th><%= t(:date_lit).humanize %></th>
                  <th width="75px">Acciones</th>
                </tr>
              </thead>

              <tbody>
                <% @meetings.each do |meeting| %>
                  <tr>
                    <td>
                      <%= link_to format_meeting_name(meeting), meeting %>
                    </td>
                    <td>
                      <%= meeting.groups.map(&:name).join(", ")  %>
                    </td>

                    <td class="text-center">
                      <%= meeting.users.count %>
                    </td>
                    <td>
                      <%= l Date.parse(meeting.date.to_s) %>
                    </td>
                    <td>

                      <%= link_to meeting_path(meeting), class: "btn btn-default btn-sm" do %> <span class="glyphicon glyphicon-zoom-in"></span> <% end %>
                      <% if can?(:edit, meeting) %>
                        <%= link_to edit_meeting_path(meeting), class: "btn btn-default btn-sm" do %> <span class="glyphicon glyphicon-edit"></span> <% end %>
                        <%= link_to meeting_path(meeting.id), method: :delete, class: "btn btn-default btn-sm", data: { confirm: t(:are_you_sure).humanize }, title: t(:destroy_meeting).humanize do %> <span class="glyphicon glyphicon-trash"></span> <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    var exportTable = '<%= 'T' if current_user.admin? %>';

    $('#datatable').DataTable({
      "sDom": '<"pull-left"' + exportTable + '>frt<"widget-foot" <"info_table pull-left"i><"pagination pull-right"p><"clearfix">>',
      "columnDefs": [ { "targets": 4, "orderable": false } ],
      "tableTools": {
        "sSwfPath": "swf/copy_csv_xls.swf",
        "aButtons": [{
          "sExtends": "csv",
          "oSelectorOpts": { filter: 'applied', order: 'current' },
          "sTitle": "listado_reuniones",
          "sButtonText": "Exportar CSV (omite filtradas)",
          "mColumns": [0, 1, 2, 3]
        },
        ]},
        "oLanguage": {
          "sSearch": "Filtrar: ",
          "sZeroRecords": "No se encontraron reuniones",
          "sInfo": "Mostrando _START_ a _END_ reuniones de un total de _TOTAL_ ",
          "sInfoEmpty": "Mostrando 0 a 0 reuniones de un total de 0",
          "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
          "oPaginate": {
            "sNext": "Siguiente <span class='glyphicon glyphicon-chevron-right'></span>",
            "sPrevious": "<span class='glyphicon glyphicon-chevron-left'></span> Anterior",
          }
        }
    });
  });
</script>

app/views/meetings/index_for_group.html.erb
<div class="container">

  <div class="page-header">
    <h1>Reuniones: <%= format_group_name(@group) %></h1>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><%= t(:recent_meetings).humanize %></h2>
        </div>
        <table class="table">
          <thead>
            <th><%= t(:date_lit).humanize %></th>
            <th><%= t(:name).humanize %></th>
          </thead>
          <tbody>
            <% @meetings.each do |meeting| %>
            <tr>
              <td><%= l meeting.date %></td>
              <td><%= link_to format_meeting_name_short(meeting), meeting %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>


    <div class="col-md-3">
      <% if can? :new, Meeting %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Navegación</h2>
        </div>
        <div class="panel-body text-center">
          <%= link_to format_group_name(@group), group_path(@group) %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>

app/views/meetings/list.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><%= t(:recent_meetings).humanize %></h2>
        </div>
        <table class="table">
          <thead>
            <th><%= t(:date_lit).humanize %></th>
            <th><%= t(:name).humanize %></th>
            <th><%= t(:attendants).humanize %></th>
          </thead>
          <tbody>
            <% @meetings.each do |meeting| %>
            <tr>
              <td><%= l meeting.date %></td>
              <td><%= link_to format_meeting_name_short(meeting), meeting %></td>
              <td><%= meeting.user_meetings.size %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>


    <div class="col-md-3">
      <% if can? :new, Meeting %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h2 class="panel-title"><%= t(:administration).humanize %></h2>
        </div>
        <div class="panel-body text-center">
          <%= link_to t(:new_meeting).humanize, new_meeting_path, class: 'btn btn-primary' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>

app/views/meetings/show.html.erb
<div class="container">

  <div class="page-header">
    <h1><%= format_meeting_name(@meeting) %></h1>
  </div>

  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Información</h3>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <td class="text-right"><strong><%= t(:description).humanize %>:</strong></td>
              <td><%= @meeting.desc %></td>
            </tr>
            <tr>
              <td class="text-right"><strong>Organiza:</strong></td>
              <td>
                <% @meeting.meeting_groups.each do |mg| %>
                  <%= link_to mg.group.display_name, mg.group %><br />
                <% end %>
              </td>
            </tr>
            <tr>
              <td class="text-right"><strong>Hora inicio:</strong></td>
              <td><%= l @meeting.start, format: :just_time unless @meeting.start.nil? %></td>
            </tr>
            <tr>
              <td class="text-right"><strong>Hora término:</strong></td>
              <td><%= l @meeting.finish, format: :just_time unless @meeting.finish.nil? %></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h3 class="panel-title"><%= t(:minutes).humanize %></h3>
        </div>
        <div class="panel-body minutes_panel_body">
          <div id="minutes_preview"></div>
          <%= hidden_field_tag :minutes, @meeting.minutes, class: "meeting_minutes_field form-control", id: "minutes_textarea", oninput: "this.editor.update()" %>
        </div>
      </div>

    </div>

    <div class="col-md-3">

      <% if can? :edit, @meeting %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h2 class="panel-title">Administración</h2>
        </div>
        <div class="panel-body text-center">
          <%= link_to 'Editar reunión', edit_meeting_path(@meeting), class: "btn btn-primary" %>
        </div>
        <ul class="list-group">
          <li class="list-group-item">
            <strong>Fecha creación:</strong><br />
            <%= l @meeting.created_at, format: :short_full %>
          </li>
          <li class="list-group-item">
            <strong>Fecha última modificación:</strong><br />
            <%= l @meeting.updated_at, format: :short_full %>
          </li>
        </ul>
      </div>
      <% end %>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Asistentes</h2>
        </div>
        <ul class="list-group">
          <% @meeting.user_meetings.each do |um| %>
            <li class="list-group-item">
              <%= render partial: 'users/user_link', locals: { user: um.user } %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

  </div>

</div>


<script>
  function Editor(input, preview) {
    this.update = function () {
      preview.innerHTML = markdown.toHTML(input.value);
      // preview.html( markdown.toHTML(input.value() ));
    };
    input.editor = this;
    this.update();
  }
  // var $ = function (id) { return document.getElementById(id); };
  new Editor(document.getElementById("minutes_textarea"), document.getElementById("minutes_preview"));
</script>