config/routes.rb
  Rails.application.routes.draw do
    root to: 'pages#welcome'

    get   '/ingresar'  => 'sessions#new'
    post  '/ingresar'  => 'sessions#create'
    delete 'salir'    => 'sessions#destroy'
    get   'mails_user_groups' => 'member_groups#mails'

    get '/users/list' => 'users#list', as: :users_list
    get '/users/manifest' => 'users#manifest', as: :users_manifest

    get '/users/manifest_file' => 'users#manifest_file', as: :users_manifest_file
    post '/users/manifest_file' => 'users#manifest_file'

    get '/users/manifest_full_file' => 'users#manifest_full_file', as: :users_manifest_full_file

    get '/meetings/list' => 'meetings#list', as: :meetings_list

    resources :users, except: [:index]
    resources :groups do
      resources :meetings do
        collection do
          get 'list' => 'meetings#index_for_group'
        end
      end
    end
    resources :meetings do
      get :autocomplete_user_name, on: :collection
    end
    resources :user_meetings
    resources :meeting_groups
    resources :member_groups
    resources :admin_groups,       only: [:create, :destroy]
    resources :password_resets,    only: [:new, :create, :edit, :update]

    resources :payments
    resources :polls do
      resources :opinions
    end
    resources :opinions
  end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  desc       :string(255)
#  type       :string(255)
#  state      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Group < ActiveRecord::Base
  # Don't use the type column for inheritance
  self.inheritance_column = nil

  STRING_MAX_LENGTH = 200
  DESC_MAX_LENGTH = 10000

  has_many :meeting_groups
  has_many :meetings, through: :meeting_groups

  has_many :admin_groups, dependent: :destroy
  has_many :admins, through: :admin_groups, source: :user

  has_many :member_groups, dependent: :destroy
  has_many :members, through: :member_groups, source: :user

  validates :name,
    presence: true,
    length:   { maximum: STRING_MAX_LENGTH }

  validates :desc,
    length:   { maximum: DESC_MAX_LENGTH }

  validates :type,
    length:   { maximum: STRING_MAX_LENGTH }

  def display_name
    case type
    when "Territory"
      "Territorio #{name}"
    when "Comission"
      "Comisión #{name}"
    when "Front"
      "Frente #{name}"
    else
      name
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  authorize_resource

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
    # @group.admin_groups = AdminGroup.new
  end

  def create
    @group = Group.new(group_params)
    create_or_update
  end

  def show
    # @meetings = @group.meetings
    @meetings = @group.meetings.order(date: :desc).limit(5)
  end

  def edit
  end

  def update
    @group.name = group_params['name']
    @group.type = group_params['type']
    @group.desc = group_params['desc']
    create_or_update
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    flash[:success] = t(:group_destroyed_successfully)
    redirect_to groups_url
  end

  private

    def create_or_update()

      if params["adminGroup"].nil?
        @group.errors.add(:moderador, " es necesario")
        render 'new'
      else
        if params["memberGroup"].nil?
          @group.errors.add(:miembro, " es necesario")
          render 'new'
        else

          if @group.save
            AdminGroup.where(:group_id => @group.id).destroy_all
            params["adminGroup"]["users"].each do |user|
              admin_group = AdminGroup.new
              admin_group.user_id = user
              admin_group.group_id = @group.id
              admin_group.save
            end

            MemberGroup.where(:group_id => @group.id).destroy_all
            params["memberGroup"]["users"].each do |user|
              member_group = MemberGroup.new
              member_group.user_id = user
              member_group.group_id = @group.id
              member_group.save
            end

            flash[:success] = action_name == 'create' ? t(:group_created_successfully) : t(:group_updated_successfully)
            # redirect_to @group
            redirect_to groups_url
          else
            render 'new'
          end
        end
      end
    end

    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :desc, :type)
    end

end

app/views/groups/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-1 col-md-10">

      <div class="panel panel-default">
        <div class="panel-heading panel-aphix">
          <% if action_name == 'new' %>
            <h4><%= t(:add_group).humanize %></h4>
          <% else %>
            <h4><%= t(:edit_group).humanize %></h4>
          <% end %>
        </div>
        <div class="panel-body">

          <%= form_for @group, html: { class: "form-horizontal" } do |f| %>

            <% if @group.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <h5><%= pluralize(@group.errors.count, "error") %>:</h5>

                <ul>
                  <% @group.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= label_tag :group_type, t(:type).humanize, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= f.select :type, options_for_select(options_for_group_type, @group.type), {}, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= label_tag :group_name, t(:name).humanize, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control", placeholder: t(:name).humanize %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label" for="group_type">Moderadores:</label>
              <div class="col-sm-10">
                <%= collection_select(:adminGroup, :users, User.all, :id, :full_name, {:selected => @group.admin_groups.map(&:user_id), include_hidden: false}, {multiple: "multiple",class: "select2-container select2-container-multi form-control ng-valid ng-dirty"}) %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label" for="group_type">Miembros:</label>
              <div class="col-sm-10">
                <%= collection_select(:memberGroup, :users, User.all, :id, :full_name, {:selected => @group.member_groups.map(&:user_id), include_hidden: false}, {multiple: "multiple", class: "select2-container select2-container-multi form-control ng-valid ng-dirty"}) %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Descripción:</label>
              <div class="col-sm-10">
                <%= f.text_area :desc, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit t(:send).humanize, class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <script type="text/javascript">
    $(document).ready(function() {
      $('#adminGroup_users').select2({
        placeholder: "Selecciona moderadores",
        allowClear: true
      });
      $('#memberGroup_users').select2({
        placeholder: "Selecciona miembros",
        allowClear: true
      });

      // $('#adminGroup_users').select2('val',['2','3']);
    });
  </script>
</div>

app/views/groups/_group_admin_li.html.erb
<li data-user-id="<%= admin_group.user_id %>">
  <span class="group_admin">
    <span class="glyphicon glyphicon-user"></span>
    <%= link_to admin_group.user.full_name, admin_group.user %>
  </span>
</li>

app/views/groups/_group_member_li.html.erb
<li data-member-id="<%= member_group.user_id %>">
  <span class="group_member">
    <span class="glyphicon glyphicon-user"></span>
    <%= link_to member_group.user.full_name, member_group.user %>
  </span>
</li>

app/views/groups/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li > <%= link_to t(:groups).humanize, groups_path %> </li>
    <li class="active"> <%= t(:list).humanize %></li>
  </ol>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading panel-aphix clearfix">
          <h4><%= t(:groups).humanize %></h4>
          <div class="pull-right">
            <% if can? :new, Group %>
              <%= link_to t(:new_group).humanize, new_group_path, class: "pull-right btn btn-primary btn-sm" %>
            <% end %>
          </div>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <table id="datatable" class="table table-bordered responsive no-wrap">
              <thead>
                <tr>
                  <th width="10px"></th>
                  <th><%= t(:name).humanize %></th>
                  <th><%= t(:type).titleize %></th>
                  <th><%= t(:members).humanize %></th>
                  <th><%= t(:meetings).humanize %></th>
                  <th width="75px">Acciones</th>
                </tr>
              </thead>

              <tbody>
                <% @groups.each do |group| %>
                  <tr>
                    <td>
                      <input type="checkbox" name="selected" class="check" value="<%= group.id %>">
                    </td>
                    <td><%= group.name %></td>
                    <td><%= t(group.type.downcase.to_sym).titleize %></td>
                    <td class="text-center"><%= group.members.count  %></td>
                    <td class="text-center"><%= group.meetings.count %></td>
                    <td>

                      <%= link_to group_path(group), class: "btn btn-default btn-sm" do %> <span class="glyphicon glyphicon-zoom-in"></span> <% end %>
                      <% if can?(:edit, group) %>
                        <%= link_to edit_group_path(group), class: "btn btn-default btn-sm" do %> <span class="glyphicon glyphicon-edit"></span> <% end %>
                        <%= link_to group_path(group.id), method: :delete, class: "btn btn-default btn-sm", data: { confirm: t(:are_you_sure).humanize }, title: t(:destroy_group).humanize do %> <span class="glyphicon glyphicon-trash"></span> <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> Lista de Correos (Copiados al portapeles)</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>
  $(function() {
    var exportTable = '<%= 'T' if current_user.admin? %>';

    var dt = $('#datatable').DataTable({
      "autoWidth": true,
      "sDom": '<"pull-left"' + exportTable + '>frt<"widget-foot" <"info_table pull-left"i><"pagination pull-right"p><"clearfix">>',
      "columnDefs": [ { "targets": [0, 5], "orderable": false } ],
      "order": [],
      "tableTools": {
        "sSwfPath": "swf/copy_csv_xls.swf",
        "aButtons": [{
          "sExtends": "csv",
          "sTitle": "listado_espacios",
          "sButtonText": "Exportar CSV (omite filtradas)",
          "mColumns": [1, 2, 3, 4],
        },{
          "sExtends": "ajax",
          "mColumns": [0],
          "bHeader": false,
          "sNewLine": ",",
          "sButtonText": "Ver lista de correos (grupos seleccionados)",
          "oSelectorOpts": { filter: 'applied', order: 'current' },
          "sAjaxUrl": "/mails_user_groups.json",
          "sAction": "flash_copy",
          "fnClick": function( nButton, oConfig, flash) {
            var sData = [];
            var self = this;
            var f = flash;
            $( "input:checkbox:checked" ).each(function(i,item){
              sData.push($(item).val());
            });
            $.when(
              $.ajax({
              "url": oConfig.sAjaxUrl,
              "data": [ { "name": "data", "value": sData }],
              "dataType": "json",
              "type": "GET",
              "cache": false,
              "async": false,
            })).then(function(data) {
              var lines = 1
              var plural = (lines==1) ? "" : "s";
              f.setText(data);
              var modal = $('#myModal');
              if (data.length == 0) {
                data = "No hay correos por mostrar. Asegurese de seleccionar los grupos";
              }
              modal.find(".modal-body").text(data)
              modal.modal('show');
            });
          }
        }
        ]},
        "oLanguage": {
          "sSearch": "Filtrar: ",
          "sZeroRecords": "No se encontraron espacios",
          "sInfo": "Mostrando _START_ a _END_ espacios de un total de _TOTAL_ ",
          "sInfoEmpty": "Mostrando 0 a 0 espacios de un total de 0",
          "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
          "oPaginate": {
            "sNext": "Siguiente <span class='glyphicon glyphicon-chevron-right'></span>",
            "sPrevious": "<span class='glyphicon glyphicon-chevron-left'></span> Anterior",
          }
        }
    });
  });

</script>

app/views/groups/show.html.erb
<div class="container">

  <div class="page-header">
    <h1><%= format_group_name(@group) %></h1>
  </div>


  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Información</h2>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <td class="text-right"><strong>Tipo:</strong></td>
              <td><%= format_group_type(@group) %></td>
            </tr>
            <tr>
              <td class="text-right"><strong>Descripción:</strong></td>
              <td><%= @group.desc %></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h2 class="panel-title"><%= t(:recent_meetings).humanize %></h2>
        </div>

        <div class="panel-body">
          <p>
            Aquí se muestran sólo las últimas reuniones del Espacio.<br />
            Ver todas las
            <%= link_to 'reuniones del espacio', list_group_meetings_path(@group) %>.
          </p>
        </div>

        <table class="table">
          <tbody>
            <% @meetings.each do |meeting| %>
              <tr>
                <td><%= link_to format_meeting_name(meeting), meeting %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-md-3">
      <% if can? :edit, @group %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h2 class="panel-title">Administración</h2>
        </div>
        <div class="panel-body text-center">
          <%= link_to 'Editar grupo', edit_group_path(@group), class: "btn btn-primary" %>
        </div>
      </div>
      <% end %>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Moderadores</h2>
        </div>
        <ul class="list-group">
          <% @group.admins.each do |user| %>
            <li class="list-group-item">
              <%= render partial: 'users/user_link', locals: { user: user } %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Miembros</h2>
        </div>
        <ul class="list-group">
          <% @group.members.each do |user| %>
            <li class="list-group-item">
              <%= render partial: "users/user_link", locals: { user: user } %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>



  <% if current_user.admin_groups.include?(@group) || current_user.admin? %>
  <!-- <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Miembros Activos</h2>
        </div>

        <table class="table">
          <tbody>
            <% @group.meetings.where() %>
          </tbody>
        </table>
      </div>
    </div>
  </div> -->
  <% end %>

</div>

<script charset="utf-8">
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>