config/routes.rb
  Rails.application.routes.draw do
    root to: 'pages#welcome'

    get   '/ingresar'  => 'sessions#new'
    post  '/ingresar'  => 'sessions#create'
    delete 'salir'    => 'sessions#destroy'
    get   'mails_user_groups' => 'member_groups#mails'

    get '/users/list' => 'users#list', as: :users_list
    get '/users/manifest' => 'users#manifest', as: :users_manifest

    get '/users/manifest_file' => 'users#manifest_file', as: :users_manifest_file
    post '/users/manifest_file' => 'users#manifest_file'

    get '/users/manifest_full_file' => 'users#manifest_full_file', as: :users_manifest_full_file

    get '/meetings/list' => 'meetings#list', as: :meetings_list

    resources :users, except: [:index]
    resources :groups do
      resources :meetings do
        collection do
          get 'list' => 'meetings#index_for_group'
        end
      end
    end
    resources :meetings do
      get :autocomplete_user_name, on: :collection
    end
    resources :user_meetings
    resources :meeting_groups
    resources :member_groups
    resources :admin_groups,       only: [:create, :destroy]
    resources :password_resets,    only: [:new, :create, :edit, :update]

    resources :payments
    resources :polls do
      resources :opinions
    end
    resources :opinions
  end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  email               :string(255)
#  name                :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  password_digest     :string(255)
#  remember_token      :string(255)
#  admin               :boolean
#  first_name          :string(255)
#  second_name         :string(255)
#  last_name           :string(255)
#  rut                 :string(255)
#  reset_digest        :string(255)
#  reset_sent_at       :datetime
#  birthdate           :date
#  city                :string(255)
#  description         :text
#  mobile_number       :string(255)
#  twitter_user        :string(255)
#  active_member_until :date
#  roles_mask          :integer
#  display_name        :string(255)
#

class User < ActiveRecord::Base
  include RunCl::ActAsRun
  include RoleModel
  attr_accessor :remember_token, :reset_token

  self.per_page = 5

  EMAIL_MAX_LENGTH    = 50
  NAME_MAX_LENGTH     = 50
  PASSWORD_MIN_LENGTH = 6
  VALID_EMAIL_REGEX   = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  MIN_RECENT_ATTENDANCES_FOR_ACTIVE_MEMBERSHIP = 6
  RECENT_TIME_MONTHS = 12

  # Never change the order of these roles!
  roles :admin, :finance_manager

  has_many :member_groups, dependent: :destroy
  has_many :groups, through: :member_groups

  has_many :admin_groups, dependent: :destroy
  has_many :agroups, through: :admin_groups, source: :group

  has_many :user_meetings, dependent: :destroy
  has_many :meetings, through: :user_meetings

  validates :email,
    presence:   true,
    uniqueness: { case_sensitive: false },
    length:     { maximum: EMAIL_MAX_LENGTH },
    format:     { with: VALID_EMAIL_REGEX   }

  validates :first_name,
    presence:   true,
    length:     { maximum: NAME_MAX_LENGTH }

  validates :second_name,
    length:     { maximum: NAME_MAX_LENGTH}

  validates :last_name,
    presence:   true,
    length:     { maximum: NAME_MAX_LENGTH }

  validates :display_name,
    length:     { maximum: NAME_MAX_LENGTH },
    allow_nil:  true

  validates :password,
    presence: true, on: :update,
    length:     { minimum: PASSWORD_MIN_LENGTH },
    confirmation: true,
    unless:      'password.nil?'

  has_secure_password validations: false

  has_run_cl :rut, uniq_run: true, run: true, if: 'rut.present?'

  # Hooks:

  before_create do
    t = User.new_token
    send_welcome_email(t)
    self.password = t
    self.admin = false
    true
  end

  before_save do
    self.email      = email.downcase
    self.rut        = Run.format(rut)
    self.first_name = first_name.titleize
    self.last_name  = last_name.titleize
  end


  # Methods:

  def admin?
    admin
  end

  def moderator?
    agroups.any?
  end

  def active_by_right?
    !active_member_until.nil? && active_member_until > Date.today
  end

  def active?
    if active_member_until.nil?
      recent_attendances >= MIN_RECENT_ATTENDANCES_FOR_ACTIVE_MEMBERSHIP
    else
      active_member_until > Date.today
    end
  end

  def recent_attendances
    from = DateTime.now.to_date - RECENT_TIME_MONTHS.months
    to   = DateTime.now.to_date
    self.meetings.where(date: (from)..(to)).count
  end

  def remember
    self.remember_token = User.digest( User.new_token )
    update_column(:remember_token, remember_token)
  end

  def forget
    update_column(:remember_token, nil)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(token, cost: cost)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_name_with_email
    "#{first_name} #{last_name} <#{email}>"
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_welcome_email(password)
    UserMailer.welcome_email(self, password).deliver
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def authenticated?(token)
    return false if remember_token.nil?
    BCrypt::Password.new(remember_token).is_password?(token)
  end

  def authenticated_reset?(token)
    return false if reset_digest.nil?
    BCrypt::Password.new(reset_digest).is_password?(token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  authorize_resource

  # GET /users
  # def index
  #   @from = params['from'] || DateTime.now.to_date - 12.months
  #   @to =   params['to'] || DateTime.now.to_date
  #   @n =    params['n'] || 12
  #   @labels = ['default', 'primary', 'success', 'info', 'warning', 'danger']
  #   @users = User.includes(:groups, :agroups).all
  # end

  def list
    @users = User.select(:id, :email, :first_name, :last_name, :admin)
    # @users = User.paginate()
    @users = User
    .select(:id, :email, :first_name, :last_name, :admin)
    .page(params[:page])
    @users_count = User.count
  end

  def manifest
  end

  def manifest_file
    min_attendances = params[:manifest][:min_attendances].to_i || 6

    start_date = Date.new params[:manifest]["start_date(1i)"].to_i, params[:manifest]["start_date(2i)"].to_i, params[:manifest]["start_date(3i)"].to_i
    end_date = Date.new params[:manifest]["end_date(1i)"].to_i, params[:manifest]["end_date(2i)"].to_i, params[:manifest]["end_date(3i)"].to_i

    # puts "min_attendances: #{min_attendances}"

    @users = User.find_by_sql ["SELECT users.id, users.first_name, users.last_name, users.email, COUNT(user_meetings.meeting_id) AS meeting_count FROM (user_meetings INNER JOIN meetings ON user_meetings.meeting_id = meetings.id INNER JOIN users ON user_meetings.user_id = users.id AND meetings.date BETWEEN ? AND ?) GROUP BY users.id HAVING COUNT(user_meetings.meeting_id) > ?", start_date, end_date, min_attendances]

    respond_to do |format|
      format.csv {
        csv_string = CSV.generate do |csv|
          csv << ["Nombre", "Apellido", "Email", "Reuniones entre #{l start_date} y #{l end_date} (al menos #{min_attendances})"]
          @users.each do |user|
            csv << [user.first_name, user.last_name, user.email, user.meeting_count]
          end
        end
        render text: csv_string
      }
    end
  end

  def manifest_full_file
    @users = User.select(:id, :first_name, :last_name, :email)

    respond_to do |format|
      format.csv {
        csv_string = CSV.generate do |csv|
          csv << ["Nombre", "Apellido", "Email"]
          @users.each do |user|
            csv << [user.first_name, user.last_name, user.email]
          end
        end
        render text: csv_string
      }
    end
  end

  # GET /users/1
  def show
    @member_group = MemberGroup.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    authorize! :edit, @user, message: t(:not_authorized)

    if current_user.agroups.any? || current_user.admin?
      render :edit_admin
    else
      render :edit
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params_admin)

    if create_or_update
      flash[:success] = t(:user_created_successfully)
      redirect_to @user
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if current_user.agroups.any? || current_user.admin?
      @user.assign_attributes(user_params_admin)
    else
      @user.assign_attributes(user_params)
    end

    if create_or_update
      flash[:success] = t(:user_updated_successfully)
      redirect_to @user
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    flash[:success] = t(:user_destroyed_successfully)
    redirect_to users_url
  end

  private


  def create_or_update
    if params["member_group"].nil? || params["member_group"]["groups"].empty?
      if @user.member_groups.empty?
        @user.errors.add(:espacio, " es necesario")
        return false
      end
    end

    success = false

    User.transaction do
      @user.save!

      if !params["member_group"].nil?
        MemberGroup.where(user_id: @user.id).destroy_all

        params["member_group"]["groups"].each do |group_id|
          member_group = MemberGroup.new(user_id: @user.id, group_id: group_id)
          member_group.save!
        end
      end

      success = true
    end

    return success
  end



  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :rut, :birthdate, :city, :description, :mobile_number, :twitter_user, :display_name)
  end

  def user_params_admin
    params.require(:user).permit(:email, :first_name, :second_name, :last_name, :password, :password_confirmation, :rut, :birthdate, :city, :description, :mobile_number, :twitter_user, :active_member_until, :display_name)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  GRAVATAR_DEFAULT_SIZE = 100
  GRAVATAR_DEFAULT_SIZE_SMALL = 10

  LOGO_RD_SMALL_URL = "https://raw.githubusercontent.com/RevolucionDemocraticaChile/demonet/development/app/assets/images/Logo_RD_small.png"
  RD_FACES_BW_URL = "https://raw.githubusercontent.com/RevolucionDemocraticaChile/demonet/development/app/assets/images/rd_faces.bw-trans.png"

  def gravatar_for(user, size = GRAVATAR_DEFAULT_SIZE)
    image_tag(gravatar_url_for(user), alt: user.name, class: "gravatar img-circle", size: "#{size}")
  end

  def gravatar_url_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{GRAVATAR_DEFAULT_SIZE}&d=#{u(RD_FACES_BW_URL)}"
  end

  def recent_attendance_for(user)
    user.meetings.where(date: (DateTime.now-6.months)..(DateTime.now)).count
  end

end

app/views/users/_membered_group_li.html.erb
<li data-group-id="<%= member_group.group_id %>">
  <span class="membered_group">
    <%= link_to member_group.group.name, member_group.group %>
    <% if removable %>
      <%= form_for member_group, html: { method: :delete }, remote: true do |f| %>
        <%= hidden_field_tag :original_controller, "users" %>
        <%= f.button type: "submit" do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      <% end %>
    <% end %>
  </span>
</li>

app/views/users/_user_link.html.erb
<%= link_to user do %>
  <%= small_avatar_for(user) %>
  <%= user.full_name %><% end %>
<% if user.admin %>
  <span class="text-danger" data-toggle="tooltip" data-placement="top" title="Un Admin tiene privilegios de Moderador en todos los Espacios.">(admin)</span>
<% end %>

app/views/users/edit_admin.html.erb
<%= render 'form_admin' %>

app/views/users/index.html.erb
<div class="container">
  <!-- <ol class="breadcrumb">
    <li > <%= link_to t(:users).humanize, users_path %> </li>
    <li class="active"> <%= t(:list).humanize %></li>
  </ol> -->

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading panel-aphix clearfix">
          <h4><%= t(:users).humanize %></h4>
          <% if current_user.admin? %>
          <div class="pull-right">
            <form action="<%= users_path %>" method="get" class="form-inline">
              <div class="form-group" style="margin-right:15px">
                <%= label_tag 'Desde'%>
                <%= text_field_tag :from, @from, class: "form-control datepicker", placeholder: @from, style: "width:100px" %>
              </div>
              <div class="form-group" style="margin-right:15px">
                <%= label_tag 'Hasta'%>
              <%= text_field_tag :to, @to, class: "form-control datepicker", placeholder: @to , style: "width:100px" %>
              </div>
              <div class="form-group" style="margin-right:15px">
                <%= label_tag 'Minima asistencias'%>
                <%= number_field_tag :n, @n, class: "form-control", placeholder: @n, style: "width:60px" %>
              </div>
              <%= submit_tag "Enviar", :name => nil, class: "btn btn-default" %>
            </form>
          </div>
          <% end %>
        </div>

        <div class="panel-body">
          <div class="table-responsive">
            <table id="datatable" class="table table-bordered">
              <thead>
                <tr>
                  <th></th> <!-- glyph icon col -->
                  <% if current_user.admin? %>
                    <th colspan="4"></th>
                  <% else %>
                    <th colspan="4"></th>
                  <% end %>
                  <% if current_user.admin? %>
                    <th></th>
                    <th style="width:40px">
                      <select id="actives_users" class="form-control">
                        <option value="">todos</option>
                        <option value="si">si</option>
                        <option value="no">no</option>
                      </select>
                    </th>
                  <% end %>
                    <th style="width:100px"><%= text_field_tag :filter_moderators, nil , class: "col-sm-12", placeholder: t(:moderators).humanize %></th>
                    <th style="width:100px"><%= text_field_tag :filter_members, nil, class: "col-sm-12", placeholder: t(:members).humanize %></th>
                  <th style="width:75px"></th>
                </tr>

                <!-- Headers -->
                <tr>
                  <th></th> <!-- glyph icon col -->
                  <th><%= t(:last_name).humanize %></th>
                  <th><%= t(:names).humanize %></th>
                  <th><%= t(:email).humanize %></th>
                  <th><%= t(:rut).humanize %></th>
                  <% if current_user.admin? %>

                    <th ><%= t(:recent_attendances).humanize %></th>
                    <th><%= t(:active).humanize %>?</th>
                  <% end %>
                  <th><%= t(:moderator_of).humanize %></th>
                  <th><%= t(:member_of).humanize %></th>
                  <th><%= t(:action).humanize %></th>
                </tr>
              </thead>

              <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <td class="text-center">
                      <% if user.active_by_right? %>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                      <% end %>
                    </td>
                    <td><%= user.last_name %></td>
                    <td><%= user.first_name %></td>
                    <td><%= user.email %></td>
                    <td><%= user.rut %></td>
                    <% if current_user.admin? %>
                      <td class="text-center" style="width: 40px">
                        <%= user.recent_attendances %>
                      </td>
                      <td class="text-center">
                        <%= if user.active? then 'si' else 'no' end %>
                      </td>
                    <% end %>
                    <td>
                      <!-- <%= user.agroups.map(&:name).join(", ")  %> -->
                      <% user.agroups.each do |g| %>
                        <%= g.name %><br />
                      <% end %>
                    </td>
                    <td>
                      <!-- <%= user.groups.map(&:name).join(", ")  %> -->
                      <!-- <%= @users.inspect %> -->
                      <!-- <%= user.groups.inspect %> -->
                      <% user.groups.each do |g| %>
                        <%= g.name %><br />
                      <% end %>
                    </td>
                    <td>
                      <%= link_to user_path(user), class: "btn btn-default btn-sm" do %>
                      <span class="glyphicon glyphicon-zoom-in"></span>
                      <% end %>
                      <% if can?(:edit, user) %>
                        <%= link_to edit_user_path(user), class: "btn btn-default btn-sm" do %> <span class="glyphicon glyphicon-edit"></span> <% end %>
                        <!-- <%= link_to user_path(user.id), method: :delete, class: "btn btn-default btn-sm", data: { confirm: t(:are_you_sure).humanize }, title: t(:destroy_user).humanize do %> <span class="glyphicon glyphicon-trash"></span> <% end %> -->
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<script>
  (function() {
    $(document).ready(function() {
      var exportTable = '<%= 'T' if current_user.admin? %>';
      var isAdmin =  '<%= '1' if current_user.admin? %>';
      var columnsAdmin = 8;
      if (!isAdmin) {
        columnsAdmin -=2;
      }

      var dt = $('#datatable').DataTable({
        "sDom": '<"pull-left"' + exportTable + '>frt<"widget-foot" <"info_table pull-left"i><"pagination pull-right"p><"clearfix">>',
        "columnDefs": [ { "targets": columnsAdmin, "orderable": false } ],
        "tableTools": {
          "sSwfPath": "swf/copy_csv_xls.swf",
          "aButtons": [{
            "sExtends": "csv",
            "sTitle": "listado_usuarios",
            "sButtonText": "Exportar CSV (omite filtradas)",
            "mColumns": [0, 1, 2, 3, 4, 5, 6, 7],
            "oSelectorOpts": { filter: 'applied', order: 'current' },
          }, {
            "sExtends": "copy",
            "sButtonText": "Copiar lista de correos",
            "mColumns": [2],
            "bHeader": false,
            "sNewLine": ",",
            "oSelectorOpts": { filter: 'applied', order: 'current' },
            "fnComplete": function(nButton, oConfig, flash, text) {
              var lines = text.split(oConfig.sNewLine).length;
              if (oConfig.bHeader) lines--;
              console.log(lines);
              if (this.s.dt.nTFoot !== null && oConfig.bFooter) lines--;
              var plural = (lines==1) ? "" : "s";
              this.fnInfo( '<h6>Lista de correos</h6>'+ '<p>Copiado '+lines+' fila'+plural+' al portapapeles.</p>', 1500);
            }
          }
          ]},
          "oLanguage": {
            "sSearch": "Filtrar: ",
            "sZeroRecords": "No se encontraron usuarios",
            "sInfo": "Mostrando _START_ a _END_ usuarios de un total de _TOTAL_ ",
            "sInfoEmpty": "Mostrando 0 a 0 usuarios de un total de 0",
            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
            "oPaginate": {
              "sNext": "Siguiente <span class='glyphicon glyphicon-chevron-right'></span>",
              "sPrevious": "<span class='glyphicon glyphicon-chevron-left'></span> Anterior",
            }
          }
      });

      // Custom search by columns
      $("thead input").on('keyup', function () {
        var COLUMN_INDEX = 6;
        var index = $("thead input").index(this);
        dt.columns( index + COLUMN_INDEX) .search( this.value ) .draw();
      });

      $("#actives_users").on("change", function () {
        var COLUMN_INDEX = 5;
        dt.columns(COLUMN_INDEX).search( this.value ) .draw();
      });

      $( "#from" ).datepicker({
        defaultDate: "+1w",
        changeMonth: true,
        numberOfMonths: 1,
        dateFormat: 'yy-mm-dd',
        onClose: function( selectedDate ) {
          $( "#to" ).datepicker( "option", "minDate", selectedDate );

        }
      });
      $( "#to" ).datepicker({
        defaultDate: "+1w",
        changeMonth: true,
        numberOfMonths: 1,
        dateFormat: 'yy-mm-dd',
        onClose: function( selectedDate ) {
          $( "#from" ).datepicker( "option", "maxDate", selectedDate );
        }
      });

    });
  })();


</script>

app/views/users/manifest.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <div class="panel panel-primary">
        <div class="panel-heading">
          <h2 class="panel-title">Generar padrón</h2>
        </div>

        <div class="panel-body">
          <%= form_tag 'manifest_file.csv', class: "form-horizontal" do %>

            <div class="form-group">
              <%= label_tag "Fecha inicio:", nil, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= date_select :manifest, :start_date, { id: 'start_date', order: [:year, :month, :day] }, { class: "form-control" } %>
              </div>
            </div>

            <div class="form-group">
              <%= label_tag "Fecha término:", nil, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= date_select :manifest, :end_date, { order: [:year, :month, :day] }, { class: "form-control" } %>
              </div>
            </div>

            <div class="form-group">
              <%= label_tag "Asistencias:", nil, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= text_field :manifest, :min_attendances, class: "form-control" %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <%= submit_tag t(:save).humanize, class: "btn btn-primary" %>
              </div>
            </div>

          <% end %>
        </div>
      </div>


      <div class="panel panel-primary">
        <div class="panel-heading">
          <h2 class="panel-title">Generar padrón completo</h2>
        </div>

        <div class="panel-body">
          <%= link_to 'Descargar padrón completo', users_manifest_full_file_path(format: :csv), class: 'btn btn-primary' %>
        </div>
      </div>

    </div>
  </div>

</div>

<script>
$(document).ready(function() {
    $('#datePicker')
        .datepicker({
            format: 'dd/mm/yyyy'
        })
        .on('changeDate', function(e) {
            // Revalidate the date field
            $('#eventForm').formValidation('revalidateField', 'date');
        });

    $('#eventForm').formValidation({
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            name: {
                validators: {
                    notEmpty: {
                        message: 'The name is required'
                    }
                }
            },
            date: {
                validators: {
                    notEmpty: {
                        message: 'The date is required'
                    },
                    date: {
                        format: 'MM/DD/YYYY',
                        message: 'The date is not a valid'
                    }
                }
            }
        }
    });
});
</script>

app/views/users/new.html.erb
<%= render 'form_admin' %>

app/views/users/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1>
          <%= image_tag(gravatar_url_for(@user), alt: @user.name, class: "gravatar img-circle", size: UsersHelper::GRAVATAR_DEFAULT_SIZE) %>
          <%= @user.full_name %>
        </h1>
      </div>
    </div>
  </div>

  <div class="row">


    <div class="col-md-offset-1 col-md-5">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><%= t(:user_information).humanize %></h2>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <td class="text-right"><strong><%= t(:email).humanize %>:</strong></td>
              <td><%= @user.email %></td>
            </tr>
            <tr>
              <td class="text-right"><strong><%= t(:name).humanize %>:</strong></td>
              <td><%= @user.full_name %></td>
            </tr>
            <% if !@user.birthdate.nil? %>
            <tr>
              <td class="text-right"><strong><%= t(:birthdate).humanize %>:</strong></td>
              <td><%= l @user.birthdate %></td>
            </tr>
            <% end %>
            <% if !(@user.city.nil? || @user.city.empty?) %>
            <tr>
              <td class="text-right"><strong><%= t(:city).humanize %>:</strong></td>
              <td><%= @user.city %></td>
            </tr>
            <% end %>
            <% if !(@user.description.nil? || @user.description.empty?) %>
            <tr>
              <td class="text-right"><strong><%= t(:description).humanize %>:</strong></td>
              <td><%= @user.description %></td>
            </tr>
            <% end %>
            <% if !(@user.twitter_user.nil? || @user.twitter_user.empty?) %>
            <tr>
              <td class="text-right"><strong><%= t(:twitter_user).humanize %>:</strong></td>
              <td><%= @user.twitter_user %></td>
            </tr>
            <% end %>
            <% if current_user.admin? || current_user.agroups.any? %>
            <tr>
              <td class="text-right"><strong><%= t(:rut).humanize %>:</strong></td>
              <td><%= @user.rut %></td>
            </tr>
            <tr>
              <td class="text-right"><strong><%= t(:mobile_number).humanize %>:</strong></td>
              <td><%= @user.mobile_number %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><%= t(:recent_meetings).humanize %></h2>
        </div>
        <% if @user.meetings.any? %>
        <table class="table">
          <thead>
            <tr>
              <th><%= t(:date_lit).humanize %></th>
              <th><%= t(:title).humanize %></th>
            </tr>
          </thead>
          <tbody>
            <% @user.meetings.order(date: :desc).each do |meeting| %>
              <tr>
                <td>
                  <%= l meeting.date %>
                </td>
                <td>
                  <%= link_to format_meeting_name(meeting), meeting %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% end %>
      </div>

    </div>

    <div class="col-md-offset-2 col-md-3">
      <% if current_user == @user %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h2 class="panel-title">Recuerda cambiar tu clave!</h2>
        </div>
        <div class="panel-body text-center">
          <%= link_to "Editar mi datos", edit_user_path(@user), class: "btn btn-primary" %>
        </div>
      </div>
      <% end %>

      <%= render partial: 'member_status_panel', locals: { user: @user, current_user: current_user } %>

      <% if @user.groups.any? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Espacios</h2>
        </div>
        <div class="panel-body">
          <% if current_user == @user %>
            Eres miembro de los siguientes Espacios:
          <% elsif %>
            Miembro de los siguientes Espacios:
          <% end %>
        </div>
        <ul class="list-group">
          <% @user.groups.each do |g| %>
            <li class="list-group-item"><%= link_to format_group_name(g), g %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

    </div>

  </div>



</div>