config/routes.rb
  Rails.application.routes.draw do
    root to: 'pages#welcome'

    get   '/ingresar'  => 'sessions#new'
    post  '/ingresar'  => 'sessions#create'
    delete 'salir'    => 'sessions#destroy'
    get   'mails_user_groups' => 'member_groups#mails'

    get '/users/list' => 'users#list', as: :users_list
    get '/users/manifest' => 'users#manifest', as: :users_manifest

    get '/users/manifest_file' => 'users#manifest_file', as: :users_manifest_file
    post '/users/manifest_file' => 'users#manifest_file'

    get '/users/manifest_full_file' => 'users#manifest_full_file', as: :users_manifest_full_file

    get '/meetings/list' => 'meetings#list', as: :meetings_list

    resources :users, except: [:index]
    resources :groups do
      resources :meetings do
        collection do
          get 'list' => 'meetings#index_for_group'
        end
      end
    end
    resources :meetings do
      get :autocomplete_user_name, on: :collection
    end
    resources :user_meetings
    resources :meeting_groups
    resources :member_groups
    resources :admin_groups,       only: [:create, :destroy]
    resources :password_resets,    only: [:new, :create, :edit, :update]

    resources :payments
    resources :polls do
      resources :opinions
    end
    resources :opinions
  end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  amount      :integer
#  date        :date
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Payment < ActiveRecord::Base

  belongs_to :user

  validates :user_id,
    presence: true

  validates :amount,
    presence: true

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  authorize_resource

  def index
    @payments = Payment.all
  end

  def new
    @payment = Payment.new
    @users = User.all
  end

  # GET /payments/1/edit
  def edit
    authorize! :edit, @payment, message: t(:not_authorized)
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    if @payment.save
      flash[:success] = t(:payment_created_successfully)
      redirect_to @payment
    else
      @users = User.all
      render 'new'
    end
  end

  def show
  end

  def edit
    @users = User.all
  end

  # PATCH/PUT /payments/1
  def update
    if @payment.update(payment_params)
      flash[:success] = t(:payment_updated_successfully)
      redirect_to @payment
    else
      render :edit
    end
  end

  # DELETE /payment/1
  def destroy
    @payment.destroy
    flash[:success] = t(:payment_destroyed_successfully)
    redirect_to payments_url
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:user_id, :amount, :date, :description)
  end

end

app/views/payments/_form.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <div class="panel panel-default">
        <div class="panel-heading panel-aphix clearfix">
          <% if action_name == 'new' %>
            <h4><%= t(:add_payment).humanize %></h4>
          <% else %>
            <h4><%= t(:edit_payment).humanize %></h4>
          <% end %>
        </div>
        <div class="panel-body">

          <%= form_for @payment, html: {class: "form-horizontal"} do |f| %>
            <% if @payment.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <h2><%= pluralize(@payment.errors.count, "error") %>:</h2>

                <ul>
                  <% @payment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.label t(:user), class: "col-sm-3 control-label", for: "payment_user_id" %>
              <div class="col-sm-9">
                <%= f.select :user_id, nil, {}, { class: "form-control" } do %>
                  <% @users.each do |user| %>
                    <%= content_tag :option, format_user_name(user), value: user.id %>
                  <% end %>
                <% end %>
              </div>

            </div>

            <div class="form-group">
              <%= f.label t(:description), class: "col-sm-3 control-label" %>
              <div class="col-sm-9">
                <%= f.text_field :description, class: "form-control", placeholder: t(:description).humanize %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label t(:amount), class: "col-sm-3 control-label" %>
              <div class="col-sm-9">
                <div class="input-group">
                  <div class="input-group-addon">$</div>
                  <%= f.number_field :amount, class: "form-control", placeholder: t(:amount).humanize %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <%= f.label t(:date_lit), class: "col-sm-3 control-label" %>
              <div class="col-sm-9">
                <%= f.date_field :date, class: "form-control", placeholder: t(:date_lit).humanize %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-3 col-sm-9">
                <% if action_name == 'new' %>
                  <%= f.submit t(:create).humanize, class: "btn btn-primary" %>
                <% else %>
                  <%= f.submit t(:send).humanize, class: "btn btn-primary" %>
                <% end%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/payments/edit.html.erb
<%= render 'form' %>

app/views/payments/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-offset-1 col-md-10">

      <h1>Pagos</h1>

      <div class="panel panel-default">
        <div class="panel-heading panel-aphix clearfix">
          <h4 class="panel-title">Pagos</h4>
          <div class="pull-right">
            <% if can? :new, Payment %>
              <%= link_to "Nuevo pago", new_payment_path, class: "btn btn-primary pull-right" %>
            <% end %>
          </div>
        </div>

        <div class="panel-body">

          <table id="datatable" class="table">
            <thead>
              <tr>
                <th></th>
                <th>ID</th>
                <th>Usuario</th>
                <th>Cantidad</th>
                <th>Fecha</th>
                <th>Decripción</th>
              </tr>
            </thead>

            <tbody>
              <% @payments.each do |payment| %>
                <tr>
                  <td>
                    <%= link_to payment_path(payment), class: "btn btn-default btn-sm" do %>
                    <span class="glyphicon glyphicon-zoom-in"/>
                    <% end %>
                    <% if can?(:edit, payment) %>
                      <%= link_to edit_payment_path(payment), class: "btn btn-default btn-sm" do %>
                      <span class="glyphicon glyphicon-edit" />
                      <% end %>
                    <% end %>
                    <%= link_to payment_path(payment.id), method: :delete, class: "btn btn-default btn-sm", data: { confirm: t(:are_you_sure).humanize }, title: t(:destroy_payment).humanize do %>
                    <span class="glyphicon glyphicon-trash" />
                    <% end %>
                  </td>
                  <td>
                    <%= format_payment_name(payment) %>
                  </td>
                  <td><%= link_to format_user_name(payment.user), payment.user %></td>
                  <td><%= payment.amount %></td>
                  <td><%= payment.date %></td>
                  <td><%= payment.description %></td>
                </tr>
              <% end %>
            </tbody>

          </table>

        </div>
      </div>


    </div>
  </div>


</div>


<script charset="utf-8">
$(document).ready(function() {
  $('#datatable').DataTable(
    {
      "oLanguage": {
        "sSearch": "Filtrar: ",
        "sZeroRecords": "No se encontraron registros",
        "sInfo": "Mostrando _START_ a _END_ de _TOTAL_ entradas",
        "sInfoEmpty": "Mostrando 0 a 0 de 0 entradas",
        "sInfoFiltered": "(filtrado de un total de _MAX_ entradas)",
        "oPaginate": {
          "sNext": "Siguiente <span class='glyphicon glyphicon-chevron-right' />",
          "sPrevious": "<span class='glyphicon glyphicon-chevron-left' /> Anterior",
        }
      }
    }
  );
});
</script>

app/views/payments/new.html.erb
<%= render 'form' %>

app/views/payments/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <h1>
        <%= format_payment_name(@payment) %>
      </h1>
    </div>
  </div>


  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Información</h3>
        </div>
        <table class="table">
          <tbody>
            <tr>
              <td class="text-right">
                <strong>Usuario:</strong>
              </td>
              <td>
                <%= format_user_name(@payment.user) %>
              </td>
            </tr>
            <tr>
              <td class="text-right">
                <strong>Cantidad:</strong>
              </td>
              <td>
                <%= @payment.amount %>
              </td>
            </tr>
            <tr>
              <td class="text-right">
                <strong>Fecha:</strong>
              </td>
              <td>
                <%= @payment.date %>
              </td>
            </tr>
            <tr>
              <td class="text-right">
                <strong>Descripción:</strong>
              </td>
              <td>
                <%= @payment.description %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>